"""Tests for scanner.pr_review_merge helpers."""

from securevibes.scanner.pr_review_merge import dedupe_pr_vulns, filter_baseline_vulns


def test_filter_baseline_vulns_excludes_pr_review_entries():
    known_vulns = [
        {"threat_id": "PR-001", "title": "Generated by PR review"},
        {"threat_id": "THREAT-1", "source": "pr_review", "title": "PR artifact"},
        {"threat_id": "THREAT-2", "finding_type": "regression", "title": "PR regression"},
        {"threat_id": "THREAT-3", "finding_type": "unknown", "title": "PR unknown"},
        {"threat_id": "THREAT-4", "title": "Baseline vuln"},
    ]

    baseline = filter_baseline_vulns(known_vulns)

    assert baseline == [{"threat_id": "THREAT-4", "title": "Baseline vuln"}]


def test_dedupe_pr_vulns_marks_unknown_overlap_as_known_vuln():
    known_vulns = [
        {
            "threat_id": "THREAT-123",
            "title": "Command injection path",
            "file_path": "src/runner.py",
        }
    ]
    pr_vulns = [
        {
            "threat_id": "PR-999",
            "title": "Command injection path",
            "file_path": "src/runner.py",
            "finding_type": "unknown",
        }
    ]

    deduped = dedupe_pr_vulns(pr_vulns, known_vulns)

    assert len(deduped) == 1
    assert deduped[0]["finding_type"] == "known_vuln"
